management.endpoints.web.exposure.include: "*"
management.endpoint.shutdown.enabled: true
management.endpoints.web.exposure.exclude: env,beans
management.endpoint.health.show-details: always
management.endpoint.health.probes.enabled: true
management.endpoint.health.group.readiness.include: readinessState,customCheck

test.list:
  - oneString: 1
    twoString: 1
  - oneString: 2
    twoString: 2
